# Generated by Django 6.0.3 on 2026-03-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='nannies.nannyprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('nanny', 'date')},
            },
        ),
    ]
