# Generated by Django 6.0.3 on 2026-03-13 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nannies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_name', models.CharField(max_length=200)),
                ('referee_email', models.EmailField(max_length=254)),
                ('referee_phone', models.CharField(blank=True, max_length=20)),
                ('relationship', models.CharField(max_length=100)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('years_known', models.PositiveIntegerField(default=0)),
                ('reference_text', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='nannies.nannyprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_references', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('identity', 'Identity Verification'), ('background_check', 'Criminal Background Check'), ('references', 'Reference Screening'), ('certifications', 'Certifications & Training')], max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='nannies.nannyprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nanny', 'step')},
            },
        ),
    ]
