# Generated by Django 6.0.3 on 2026-03-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('family_basic', 'Family Basic (Free)'), ('family_premium', 'Family Premium'), ('family_elite', 'Family+ (Elite)'), ('nanny_standard', 'Nanny Standard')], max_length=30),
        ),
    ]
