import { useState } from 'react'
import { FileText, Download, Clock, Check, Pen } from 'lucide-react'
import { cn } from '@/lib/utils/cn'
import { useBookings } from '@/queries/useBookings'
import { bookingService } from '@/services/bookingService'
import { Skeleton } from '@/components/ui/Skeleton'
import { EmptyState } from '@/components/ui/EmptyState'
import { formatDate } from '@/lib/utils/formatDate'
import { formatCurrency } from '@/lib/utils/formatCurrency'
import type { Booking } from '@/types/booking'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

const statusStyles: Record<string, string> = {
  active: 'bg-success-50 text-success-700',
  pending: 'bg-warning-50 text-warning-700',
  expired: 'bg-cream-200 text-charcoal-muted',
  signed: 'bg-success-50 text-success-700',
  unsigned: 'bg-warning-50 text-warning-700',
}

function getContractStatus(booking: Booking): string {
  if (['completed', 'cancelled'].includes(booking.status)) return 'expired'
  if (['confirmed', 'in_progress', 'in-progress'].includes(booking.status)) return 'active'
  return 'pending'
}

function getBookingTypeLabel(type: string): string {
  switch (type) {
    case 'one_off': return 'One-off'
    case 'regular': return 'Regular'
    case 'live_in': return 'Live-in'
    case 'one-time': return 'One-time'
    case 'recurring': return 'Recurring'
    case 'overnight': return 'Overnight'
    case 'travel': return 'Travel'
    default: return type || '?'
  }
}

function getNannyName(b: Booking): string {
  if (b.nanny_card) {
    return `${b.nanny_card.first_name || ''} ${b.nanny_card.last_name || ''}`.trim() || '?'
  }
  return '?'
}

export function ContractsPage() {
  const queryClient = useQueryClient()
  const { data, isLoading, isError } = useBookings()
  const [selectedBookingId, setSelectedBookingId] = useState<number | null>(null)
  const [showSignModal, setShowSignModal] = useState(false)
  const [signature, setSignature] = useState('')

  // Filter bookings that are confirmed/in-progress (contract-worthy)
  const bookings = (data?.results ?? []).filter(
    (b) => ['confirmed', 'accepted', 'in_progress', 'in-progress', 'completed'].includes(b.status)
  )

  // Fetch contract for selected booking
  const { data: contract } = useQuery({
    queryKey: ['contract', selectedBookingId],
    queryFn: () => bookingService.getContract(String(selectedBookingId)),
    enabled: !!selectedBookingId,
  })

  const createContractMutation = useMutation({
    mutationFn: ({ bookingId, terms }: { bookingId: string; terms: string }) =>
      bookingService.createContract(bookingId, terms),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contract'] })
    },
  })

  const signContractMutation = useMutation({
    mutationFn: ({ bookingId, sig }: { bookingId: string; sig: string }) =>
      bookingService.signContract(bookingId, sig),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contract'] })
      setShowSignModal(false)
      setSignature('')
    },
  })

  const handleCreateContract = (bookingId: number) => {
    const nannyName = getNannyName(bookings.find(b => b.id === bookingId)!)
    const terms = `Standard childcare agreement between family and ${nannyName}. Both parties agree to the terms of service as outlined on The Nest Nanny platform.`
    createContractMutation.mutate({ bookingId: String(bookingId), terms })
    setSelectedBookingId(bookingId)
  }

  const handleSign = () => {
    if (!selectedBookingId || !signature.trim()) return
    signContractMutation.mutate({ bookingId: String(selectedBookingId), sig: signature.trim() })
  }

  const handleDownload = (booking: Booking) => {
    const nannyName = getNannyName(booking)
    const text = `CONTRACT\n\n${getBookingTypeLabel(booking.booking_type)} agreement with ${nannyName}\nStart: ${booking.start_date}\nRate: ${formatCurrency(parseFloat(booking.total_amount || '0'), booking.currency)}\n\nGenerated by The Nest Nanny`
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `contract-${booking.id}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div>
      <p className="section-label mb-2">FAMILIES</p>
      <div className="mb-6">
        <h1 className="font-serif text-heading-lg text-charcoal">Contracts</h1>
        <p className="mt-1 text-charcoal-muted">Manage your care agreements</p>
      </div>

      {isLoading ? (
        <div className="space-y-4">
          {Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="rounded-2xl border border-cream-300 bg-white p-6 shadow-card">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-4">
                  <Skeleton width={44} height={44} />
                  <div className="space-y-2">
                    <Skeleton width={200} height={16} />
                    <Skeleton width={160} height={12} />
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <Skeleton width={60} height={24} />
                  <Skeleton width={32} height={32} />
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : isError ? (
        <div className="rounded-2xl border border-cream-300 bg-white p-12 text-center shadow-card">
          <p className="font-serif text-lg text-charcoal">Could not load contracts</p>
          <p className="mt-1 text-sm text-charcoal-muted">Please try again later.</p>
        </div>
      ) : bookings.length === 0 ? (
        <EmptyState
          icon={<FileText className="h-8 w-8" />}
          title="No contracts yet"
          description="Contracts will appear here once you confirm bookings with nannies."
        />
      ) : (
        <div className="space-y-4">
          {bookings.map((b) => {
            const contractStatus = getContractStatus(b)
            const nannyName = getNannyName(b)
            const isSelected = selectedBookingId === b.id

            return (
              <div
                key={b.id}
                className="rounded-2xl border border-cream-300 bg-white p-6 shadow-card"
              >
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-4">
                    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gold-400/10 text-gold-400">
                      <FileText className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="font-medium text-charcoal">
                        {getBookingTypeLabel(b.booking_type)} contract with {nannyName}
                      </h3>
                      <div className="mt-1 flex items-center gap-3 text-sm text-charcoal-muted">
                        {b.start_date && (
                          <span>Started {formatDate(b.start_date)}</span>
                        )}
                        {b.hours_per_week && (
                          <span className="flex items-center gap-1">
                            <Clock className="h-3.5 w-3.5" /> {b.hours_per_week} hrs/wk
                          </span>
                        )}
                        <span>{formatCurrency(parseFloat(b.total_amount || '0'), b.currency)}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={cn('pill-badge text-xs font-medium capitalize', statusStyles[contractStatus] || 'bg-cream-200 text-charcoal-muted')}>
                      {contractStatus}
                    </span>
                    <button
                      onClick={() => setSelectedBookingId(isSelected ? null : b.id)}
                      className="rounded-lg px-3 py-1.5 text-xs font-medium text-gold-400 hover:bg-cream-100"
                    >
                      {isSelected ? 'Hide' : 'View'}
                    </button>
                    <button
                      onClick={() => handleDownload(b)}
                      className="rounded-lg p-2 text-charcoal-muted hover:bg-cream-200 hover:text-charcoal"
                    >
                      <Download className="h-4 w-4" />
                    </button>
                  </div>
                </div>

                {/* Expanded contract details */}
                {isSelected && (
                  <div className="mt-4 border-t border-cream-200 pt-4">
                    {contract ? (
                      <div className="space-y-3">
                        <div className="rounded-lg bg-cream-50 p-4 text-sm text-charcoal-muted">
                          {contract.terms}
                        </div>
                        <div className="flex items-center gap-4 text-sm">
                          <span className="flex items-center gap-1">
                            {contract.family_signed ? (
                              <Check className="h-4 w-4 text-success-500" />
                            ) : (
                              <Clock className="h-4 w-4 text-warning-500" />
                            )}
                            Family: {contract.family_signed ? 'Signed' : 'Unsigned'}
                          </span>
                          <span className="flex items-center gap-1">
                            {contract.nanny_signed ? (
                              <Check className="h-4 w-4 text-success-500" />
                            ) : (
                              <Clock className="h-4 w-4 text-warning-500" />
                            )}
                            Nanny: {contract.nanny_signed ? 'Signed' : 'Unsigned'}
                          </span>
                        </div>
                        {!contract.family_signed && (
                          <>
                            {showSignModal ? (
                              <div className="space-y-2">
                                <input
                                  type="text"
                                  value={signature}
                                  onChange={(e) => setSignature(e.target.value)}
                                  placeholder="Type your full name to sign"
                                  className="w-full rounded-xl border border-cream-300 bg-white px-4 py-2.5 text-sm focus:border-gold-400 focus:outline-none"
                                />
                                <div className="flex gap-2">
                                  <button
                                    onClick={handleSign}
                                    disabled={!signature.trim() || signContractMutation.isPending}
                                    className="rounded-lg bg-gold-400 px-4 py-2 text-xs font-medium text-white hover:bg-gold-500 disabled:opacity-50"
                                  >
                                    {signContractMutation.isPending ? 'Signing...' : 'Sign Contract'}
                                  </button>
                                  <button
                                    onClick={() => setShowSignModal(false)}
                                    className="rounded-lg border border-cream-300 px-4 py-2 text-xs font-medium text-charcoal hover:bg-cream-100"
                                  >
                                    Cancel
                                  </button>
                                </div>
                              </div>
                            ) : (
                              <button
                                onClick={() => setShowSignModal(true)}
                                className="flex items-center gap-1.5 rounded-lg bg-gold-400 px-4 py-2 text-xs font-medium text-white hover:bg-gold-500"
                              >
                                <Pen className="h-3.5 w-3.5" />
                                Sign Contract
                              </button>
                            )}
                          </>
                        )}
                      </div>
                    ) : (
                      <div className="space-y-3">
                        <p className="text-sm text-charcoal-muted">No contract created yet for this booking.</p>
                        <button
                          onClick={() => handleCreateContract(b.id)}
                          disabled={createContractMutation.isPending}
                          className="rounded-lg bg-gold-400 px-4 py-2 text-xs font-medium text-white hover:bg-gold-500 disabled:opacity-50"
                        >
                          {createContractMutation.isPending ? 'Creating...' : 'Create Contract'}
                        </button>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

export default ContractsPage
